import { GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import clientPromise from '../../lib/mongodb';

type Project = {
  _id: string;
  name: string;
  description: string;
};

type HomeProps = {
  projects: Project[];
};

const Home: React.FC<HomeProps> = ({ projects }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My Portfolio
        </h1>
        <div className={styles.grid}>
          {projects.map((project) => (
            <div key={project._id} className={styles.card}>
              <h3>{project.name}</h3>
              <p>{project.description}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const client = await clientPromise;
  const db = client.db('portfolio');
  const projects = await db.collection('projects').find({}).toArray();

  return {
    props: { projects: JSON.parse(JSON.stringify(projects)) },
  };
};

export default Home;
